server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: job-search-api
  
  datasource:
    url: jdbc:mysql://localhost:3306/job_search_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Bot Service Configuration
bot:
  service:
    url: http://localhost:8081
    timeout: 5000

# Logging Configuration
logging:
  level:
    com.rbc: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# CORS Configuration
cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true 