server:
  port: 8081
  servlet:
    context-path: /bot/v1

spring:
  application:
    name: job-search-bot
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# API Service Configuration
api:
  service:
    url: http://localhost:8080/api/v1
    timeout: 5000

# AI Model Configuration (Placeholder for future integration)
ai:
  models:
    job-recommendation:
      enabled: false
      model-path: "models/job-recommendation"
    skill-matching:
      enabled: false
      model-path: "models/skill-matching"
    chatbot:
      enabled: false
      model-path: "models/chatbot"

# Logging Configuration
logging:
  level:
    com.rbc: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# CORS Configuration
cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true 

# Gemini API Configuration
# Replace with your actual Gemini API endpoint and key
gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=
    key: AIzaSyDBVqmV0bDW2D3pXhDF8sFFuO_lLNTdnrE